# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 14:50
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180912_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Муниципальное образование', 'verbose_name_plural': 'Муниципальные образования'},
        ),
        migrations.AlterModelOptions(
            name='objectinfo',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Видовая принадлежность', 'verbose_name_plural': 'Видовые принадлежности'},
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='id_openData',
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID opendata.mkrf.ru'),
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, verbose_name='slugURL'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='OKN_in_ensemble',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='ОКН входит в ансамбль (да/нет)'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='actual_address',
            field=models.TextField(blank=True, null=True, verbose_name='Актуальный адрес'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='affiliation_U',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Принадлежность к ЮНЭСКО'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='document_on_approved_security',
            field=models.TextField(blank=True, null=True, verbose_name='Документ об утвержденых зонах охраны'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='esp_valuable_object',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Особо ценный объект'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='fullAddress',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='gen_species_appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Species', verbose_name='Общая видовая принадлежность'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_docs_boundaries',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Наличие документов о границах территории ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_docs_of_aprroval',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Наличие документов об утвержденых зонах охраны'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_passport_OKN',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет'), ('In_work', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие паспорта ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_rights',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Наличие зарегистрированных прав/обременений'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_security_obligation',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет'), ('In_work', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие охранного обязательства ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='information_sign',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет'), ('In_work', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие уcтановленной информационной надписи установленного образца'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='information_sign_conformity',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, null=True, verbose_name='Наличие информационной надписи, но не соответствующей требованиям'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='information_sign_photo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.image_folder, verbose_name='Фотография информационной надписи'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Locality', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='management',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Под чьим управлением'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Municipality', verbose_name='Муниципальное образование'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='nativeName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='owner_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контактные данные собственника ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.image_folder, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='req_of_approval',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты об утверждении границ территории'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='requisites_and_title',
            field=models.TextField(blank=True, null=True, verbose_name=' Реквизиты и наименование акта органа государственной власти о постановке на государственную охрану объекта культурного наследия'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL адрес'),
        ),
    ]
